server:
  port: 8080
  tomcat:
      uri-encoding: UTF-8
  servlet:
      context-path: /api
      session:
        cookie:
          path: /
spring:
  profiles:
    active: dev
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/gecris?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    username: root
#    password: root
  redis:
    host: localhost
#    host: localhost
    port: 6379
    timeout: 100000
    password: iischina
    jedis:
      pool:
        max-wait: 10000